name: draft-relese

# Controls when the action will run.
on:
  # Triggers the workflow on "version.py" file changed
  push:
    paths:
      - 'testfile.txt'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: clone FireDM
        run: git clone https://github.com/firedm/FireDM

      - name: get version name and changelog
        run: |
          echo "version=$(cat ./FireDM/firedm/version.py | grep -Po '\d+\.\d+\.\d+')" >> $GITHUB_ENV
          echo "changelog=$(sed 's/\r$//' ./FireDM/ChangeLog.txt | sed -e '/^$/,$d')" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.version }}
          release_name: FireDM version ${{ env.version }}
          body: |
            # Release info:
            **Windows: [.zip file]**
            - Portable version for windows 32bit and 64bit, no installation needed, just extract to any folder and run FireDM.exe file
            - ffmpeg.exe included, you can download latest version [here](https://ffmpeg.zeranoe.com/builds/)
            - The binary version ".exe" prepared by "cx_freeze" on python 3.8, windows8x32bit
            ---

            **Linux: [.AppImage file]**
            - AppImage file, portable, no installation needed, download and make file executable by right clicking the file>Properties>Permissions>Allow executing file as a program, or from terminal by `chmod +x FireDM_xxx.AppImage`
            - ffmpeg is not included in this image and must be available on your system, to check for ffmpeg use this command:
            ```
            which ffmpeg
            # expected output
            /usr/bin/ffmpeg
            ```
            to install ffmpeg you can `sudo apt install ffmpeg` on debian based or ` sudo pacman -S ffmpeg` on Arch based
            - The binary version ".AppImage" prepared by "appimage-builder" on linuxmint, and tested on ubuntu 20.04 and Manjaro kde
            ---

            **changelog:**
            ${{ env.chagelog }}

          draft: true
          prerelease: false

