# This is a basic workflow to help you get started with Actions

name: appimage-build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  #release:
  #  types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
   
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: create binaries
        run: |
          #sudo apt-get install tree
          git clone https://github.com/firedm/FireDM.git
          cp ./appimage-quickbuild.py ./FireDM/scripts/appimage/
          cd ./FireDM/scripts/appimage
          python3 ./appimage-quickbuild.py
          ls .

      # upload file to github release page 00
      #- name: Upload the artifacts
        #uses: skx/github-action-publish-binaries@master
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #with:
          #args: './FireDM/scripts/appimage/*.AppImage ./FireDM/scripts/exe_build/*.zip'
